### ISSUE TITLE
getROI() does not work for Scoord3D objects of type Circle

### ISSUE THREAD

**Issue by hackermd** [dcmjs-org/dicom-microscopy-viewer#12]
Not all classes derived from `Scoord3D` have a `coordinates` attribute. For example, `Circle` doesn't.

This assumption currently breaks the `getROI()` viewer method:
https://github.com/dcmjs-org/dicom-microscopy-viewe/blob/0aa5e768029a5a5d6b9c8fa224081218dae76b6f/src/api.js#L731-L737

There are further issues with this approach:

- The length of the value of the `coordinates` attribute of an object of type `Point` should no longer be 2, but 3 (since we switched from `Scoord` to `Scoord3D`)
- The value of the `coordinates` attribute of an object of type `Point` should be an array of numbers of length 3.  [Changing the value to an array of arrays](https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/0aa5e768029a5a5d6b9c8fa224081218dae76b6f/src/api.js#L735) would break the [graphicData()](https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/0aa5e768029a5a5d6b9c8fa224081218dae76b6f/src/scoord3d.js#L34-L36) getter, which would return incorrect graphic data.
- The coordinates returned by `_geometry2Scoord3D()` should already be in the correct format, i.e. in the slide coordinate system in millimeter unit. This [line](https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/0aa5e768029a5a5d6b9c8fa224081218dae76b6f/src/api.js#L737) should thus not be necessary.

**Comment by biharck** [comment]
Fixed at https://github.com/dcmjs-org/dicom-microscopy-viewer/pull/10/commits/04d200a770fa53d68dd58ade2779dd3e7fb2f85a
