### ISSUE TITLE
Check constructor arguments of Scoord3D classes

### ISSUE THREAD

**Issue by hackermd** [dcmjs-org/dicom-microscopy-viewer#13]
Currently, there are no checks for the arguments of the constructor of classes derived from `Scoord3D`. This is dangerous because these values are returned by the `graphicData()` getter, which is indented to return the coordinates in the format required by DICOM.
We should check for the type (e.g. `Array` or `Number`) and as well as the values (e.g. whether first and last array element are identical for `Polygon`).

For example:

```javascript
class Point extends Scoord3D {

  constructor(coordinates) {
    super()
    if (!Array.isArray(coordinates)) {
        console.error('coordinates of Point must be an array')
    }
    if (coordinates.length !== 3) {
        console.error('coordinates of Point must be an array of length 3')
    }
    this.coordinates = coordinates
  }

  get graphicData() {
    return this.coordinates;
  }

  get graphicType() {
    return 'POINT';
  }

}
```

**Comment by hackermd** [comment]
We may even want to make these attribute "private" to prevent users from abusing them. We want them to use `graphicData()`.

**Comment by hackermd** [comment]
Related to #12

**Comment by hackermd** [comment]
A good overview of graphic data for each graphic type can be found in [PS3.3 C.10.5.1.2 Graphic Data and Graphic Type](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.10.5.html#sect_C.10.5.1.2)

**Comment by biharck** [comment]
Fixed at https://github.com/dcmjs-org/dicom-microscopy-viewer/commit/8af8a94ce98a32de3491f60e7a4a75742a0b17c2
