### ISSUE TITLE
Make coordinates property of Scoord3D objects read-only

### ISSUE THREAD

**Issue by hackermd** [dcmjs-org/dicom-microscopy-viewer#15]
We need to prevent that users modify the `coordinates` property of `Scoord3D` objects. Otherwise, the value returned by `graphicData` getter may no longer be correct, i.e. no longer be in the format required for DICOM SR.

**Comment by biharck** [comment]
I think it was already solved with https://github.com/dcmjs-org/dicom-microscopy-viewer/commit/8af8a94ce98a32de3491f60e7a4a75742a0b17c2
