### ISSUE TITLE
Error when escaping during drawing

### ISSUE THREAD

**Issue by biharck** [dcmjs-org/dicom-microscopy-viewer#16]
Currently, if I start drawing something and press "esc" the tool will fail

![escaping_issue](https://user-images.githubusercontent.com/1713255/54524955-ec785b00-4951-11e9-8add-f14b795e2453.gif)

**Comment by swederik** [comment]
I would suggest removing the `keydown` functionality or making it optional. Once this library is embedded into larger applications the hotkey management will be handled at the application level anyway. We ended up removing the built-in hotkeys from Cornerstone Tools for this reason.

**Comment by hackermd** [comment]
I agree. Let's remove these event listeners from the library. They can be implemented by an application if desired.

**Comment by biharck** [comment]
Thank you guys for the inputs.
The key down eventListener was removed at https://github.com/dcmjs-org/dicom-microscopy-viewer/tree/removing-keydown-event

**Comment by hackermd** [comment]
Thanks @biharck. Please feel free to go ahead and merge #17.
