### ISSUE TITLE
Add event handlers or callbacks for graphical annotations

### ISSUE THREAD

**Issue by hackermd** [dcmjs-org/dicom-microscopy-viewer#3]
We need some event listeners or callbacks that allow us to add custom behavior to the viewer. For example, an application may want to automatically compute measurements for each geometry that has been drawn by a user and update the measurements when a user modifies the geometry.

Openlayers exposes several types of events that we could leverage for this purpose. However, we don't want to rely on Openlayer events directly, but want to fully abstract the Openlayers API.

The following events fire for `drawInteraction`, `selectInteraction`, and `modifyInteraction`, respectively:

- [DrawEvent](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-DrawEvent.html)
- [SelectEvent](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Select-SelectEvent.html)
- [ModifyEvent](https://openlayers.org/en/latest/apidoc/module-ol_interaction_Modify.ModifyEvent.html)

In addition, Openlayers fires an event whenever a geometry gets drawn and collected:

- [CollectionEvent](https://openlayers.org/en/latest/apidoc/module-ol_Collection.CollectionEvent.html)

We may want to allow users of the library to provide callbacks, which could be specified as an option for the constructor and/or for `activateDrawInteraction`, `activateSelectInteraction`, and `activateModifyInteraction`.

**Comment by biharck** [comment]
Hello, @hackermd I created an example of the event strategy which is basically a **publisher** which publishes a dummy message and **subscribers** that subscribes a specific event.
Could you please take a look at the example below including your thoughts about this strategy?

https://codepen.io/biharck/pen/wNNegK?editors=1010

Cheers,

**Comment by swederik** [comment]
Thanks @biharck!

Yes adding a layer internally to capture OpenLayers events and export dicom-microscopy-viewer CustomEvents makes sense.

For reference, CornerstoneTools emits the following events: https://github.com/cornerstonejs/cornerstoneTools/blob/master/src/events.js

The most relevant here would probably be:

- `MEASUREMENT_ADDED` and `MEASUREMENT_REMOVED` could be emitted when we capture the relevant OpenLayers DrawEvent (for initial add) and CollectionEvent (for remove) internally.
- `MEASUREMENT_MODIFIED` could be emitted when we capture an OpenLayers ModifyEvent internally
- `MEASUREMENT_COMPLETED`: i.e. the user has finished drawing the tool (in progress: https://github.com/cornerstonejs/cornerstoneTools/pull/845). Could be emitted when we capture the 'add' in a CollectionEvent internally.

Looks like we would also want `MEASUREMENT_SELECTED` (based on SelectEvent) as well, and possibly `INTERACTION_ACTIVATED` with a 'type' (and possibly tool?) parameter ('draw', 'select', 'modify') or something, which could address @hackermd's last point.

**Comment by hackermd** [comment]
thanks @biharck 

I think the **publisher**/**subscribers** is a good approach.

The question is what objects should be provided together with the event? Openlayer events provide a [Feature](https://openlayers.org/en/latest/apidoc/module-ol_Feature-Feature.html) object. Custom viewer events should then probably provide a `ROI` object.

Analogous to @swederik proposal, I would call the events `ROI_ADDED`, `ROI_REMOVED`, `ROI_DRAWN`, `ROI_SELECTED`, and `ROI_MODIFIED`. I would use the term `ROI` rather than `MEASUREMENT`, since viewer events effect only a region rather a measurement (from a DICOM SR perspective).

**Comment by biharck** [comment]
Hello, I create a PR with suggested implementation. Would you guys mind to have a look, please?
https://github.com/dcmjs-org/dicom-microscopy-viewer/pull/10

Cheers,

**Comment by hackermd** [comment]
Closing this, since the PR is about to be merged.
