### ISSUE TITLE
Hardcoded mimetype has quotation mark issue

### ISSUE THREAD

**Issue by swederik** [dcmjs-org/dicom-microscopy-viewer#32]
Here we are passing the mimetype to dicomweb-client:

https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/c706f918c0387c40f34cff922d6200e18d43b9ce/src/api.js#L498

We are passing `image/jpeg; transfer-syntax=1.2.840.10008.1.2.4.50`.

dicomweb-client is wrapping this with `type="${blah}"`

This means that the quotation marks end up in the wrong place, and we end up with:
`type="image/jpeg; transfer-syntax=1.2.840.10008.1.2.4.50"` which is invalid. dcm4chee doesn't seem to care, but Google Cloud Healthcare API is more stringent and so we end up with 406 errors. It's weird because I swear I tested this before merging and it was working.

I'm not sure if this is something we should fix here or in dicomweb-client. We should probably just finish off this PR: https://github.com/dcmjs-org/dicomweb-client/pull/16 which makes dwc act more like the Python version.

Just posting this for visibility.

**Comment by swederik** [comment]
Looks like Orthanc is also failing on this Accept header issue (https://github.com/OHIF/Viewers/issues/624)

**Comment by hackermd** [comment]
Fixed with https://github.com/dcmjs-org/dicomweb-client/commit/bc35f099d6a56280845c61a1c4da3369c54fa1ff

**Comment by swederik** [comment]
Had to reopen this. The commit above actually re-broke the accept header in 0.5.1 which was fixed in 0.5.0. Duplicating my comment here so it's easier to keep track of things.

The Accept header issue should have been fixed by the mediaTypes PR, sorry if that wasn't clear.

The last quotation mark should only surround type="${blah}", **not** the entire piece "type={blah}; transfer-syntax={blah}.

You can see the example here under the Note: http://dicom.nema.org/medical/dicom/current/output/html/part18.html#sect_8.7.3.5.2

It should look like this: `Accept: multipart/related; type="application/dicom";transfer-syntax=1.2.840.10008.1.2.4.50;boundary=**, multipart/related; type="application/dicom";transfer-syntax=1.2.840.10008.1.2.4.57;q=0.5;boundary=**`

**Comment by hackermd** [comment]
@swederik Sorry, I didn't realize that you had already fixed it. Can you please confirm whether this now works with [release v0.5.2](https://github.com/dcmjs-org/dicomweb-client/releases/tag/v0.5.2)?

**Comment by swederik** [comment]
Yep 0.5.2 works! Thanks!
