### ISSUE TITLE
getALLROIs does not work (numberOfMeasurements is undefined)

### ISSUE THREAD

**Issue by swederik** [dcmjs-org/dicom-microscopy-viewer#5]
See https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/00e0ff235d7aec49e6a3447d5781a3a0eb96ef92/src/api.js#L708

**Comment by biharck** [comment]
Fixed at https://github.com/dcmjs-org/dicom-microscopy-viewer/commit/9e63f9b0c1c6a2ab786de310e13cced54f257c21
