### ISSUE TITLE
getROI should fail gracefully if there is no ROI at that index

### ISSUE THREAD

**Issue by swederik** [dcmjs-org/dicom-microscopy-viewer#6]
dicom-microscopy-viewer.js:51463 Uncaught TypeError: Cannot read property 'getGeometry' when I called `getROI(0)` and hadn't drawn anything yet.

**Comment by biharck** [comment]
Fixed at https://github.com/dcmjs-org/dicom-microscopy-viewer/commit/c5330c07b7f53a97e3024fc5408cb387cdc56b1a
