### ISSUE TITLE
Unclear how to obtain referenced instance / frame from ROI / scoord

### ISSUE THREAD

**Issue by swederik** [dcmjs-org/dicom-microscopy-viewer#7]
We might have missed it, but from an ROI, it wasn't obvious how to obtain the frame that the measurement was made upon. We have coordinates, but I'm not sure that's sufficient. It depends on how we encode the measurements in dcmjs (@hackermd mentioned scoord3d at one point, maybe @fedorov or @pieper have some other ideas).

Note: We started making a dcmjs adapter here:
https://github.com/dcmjs-org/dcmjs/tree/dicom-microscopy-adapter

**Comment by hackermd** [comment]
We should use `Scoord3D` instead of `Scoord` and specify coordinates relative to the three-dimensional slide coordinate system rather than relative the total pixel matrix or an individual frame.

**Comment by hackermd** [comment]
To this end, we need to transform the map coordinates to the slide-based coordinates in millimeter units:
 https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/00e0ff235d7aec49e6a3447d5781a3a0eb96ef92/src/api.js#L260

Alternatively, we may be able to handle this directly via Openlayer `Projection`:
https://github.com/dcmjs-org/dicom-microscopy-viewer/blob/00e0ff235d7aec49e6a3447d5781a3a0eb96ef92/src/api.js#L414

**Comment by swederik** [comment]
I think I'll close this since SCOORD3D does not require you to specify a ReferencedSOPSequence.
